server:
  port: 8082
  servlet:
    context-path: /ui
    session:
      cookie:
        name: UISESSION
security:
  oauth2:
    client:
      client-id: ClientId
      client-secret: secret
      access-token-uri: http://localhost:8087/auth/oauth/token
      user-authorization-uri: http://localhost:8087/auth/oauth/authorize
    resource:
      user-info-uri: http://localhost:8087/auth/rest/test/principal

spring:
  thymeleaf:
    cache: false
